workspace:
  base: /srv/app
  path: src/github.com/appleboy/drone-scp

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    commands:
      - make vet
      - make lint
      - make test
      - make coverage
      - make build
      # build binary for docker image
      - make static_build

  release:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
